language: julia

os:
  # - osx
  # - linux
  - windows

julia:
  - 1.2
  # - nightly

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
