# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - freebsd
  # We cannot test FFMPEG on Windows because of
  # https://travis-ci.community/t/any-chance-of-providing-an-environment-with-desktop-experience/1024
  # - windows
arch:
  - x64
  - x86
  - arm64
julia:
  - 1.5
  - 1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  exclude:
    - os: osx
      arch: x86
    - os: freebsd
      arch: x86
    - os: osx
      arch: arm64
    - os: freebsd
      arch: arm64
    # - os: windows
    #   arch: arm64
    - julia: nightly
      arch: arm64
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

cache:
  directories:
  - $HOME/.julia/artifacts
