name: Run tests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
    tags: '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['lts', '1']
        julia-arch: [x64, x86, aarch64]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: ubuntu-latest
            julia-arch: aarch64
          - os: windows-latest
            julia-arch: aarch64
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-runtest@v1
